### ISSUE TITLE
Listing Account Transactions fails

### ISSUE THREAD

**Issue by gugray** [blockwatch-cc/tzstats-go#2]
If I follow the steps on the readme page to retrieve an account's transactions, the call deterministically fails with the error below.

```
2021/11/20 17:18:41 404 Not Found: {"errors":[{"code":1000,"detail":"Unrecognized request URL (GET: /explorer/contract/tz1at5SeBtz5fKij7Ba3vJDsaPASkdvqM16f/operations).","message":"resource not found","request_id":"77e9dd08-6330-4e6e-a4d2-73e2bd4719e5","scope":"NotFound","status":404}]} GET HTTP/1.1 https://api.tzstats.com/explorer/contract/tz1at5SeBtz5fKij7Ba3vJDsaPASkdvqM16f/operations?limit=100&order=desc
```

For reference, the calling code is:
```
addr := tezos.MustParseAddress("tz1at5SeBtz5fKij7Ba3vJDsaPASkdvqM16f")
params := tzstats.NewOpParams().WithLimit(100).WithOrder(tzstats.OrderDesc)
ops, err := client.GetAccountOps(ctx, addr, params)
if err != nil {
    log.Fatal(err)
}
```

**Comment by echa** [comment]
Thanks, fixed.

**Comment by gugray** [comment]
That was fast :)

What's your process for publishing an updated package?

**Comment by echa** [comment]
I was literally just working on it when I saw your issue. Updates happen via Go module versioning, but you can usually also do. 

`go get -u blockwatch.cc/tzstats-go@master` 

We're using this library internally for a lot of our downstream tools that work with TzIndex, so master is usually stable.

Right now we're preparing the next API release which will be live on api.staging.tzstats.com in a short while.
